### ISSUE TITLE
[Bug]: 포스트 개행 안되는 이슈

### ISSUE THREAD

**Issue by lifthus** [lifthus/lifthus_front#20]
### What happened?

포스트에서
```
abc
def
```
라고 써도, 제출하고나면 화면에 출력은
```
abd def
```
라고 출력되네요.

### What operating system are you seeing the problem on?

Mac

### What browser are you seeing the problem on?

Chrome

### Agreement

- [X] I've checked if there's any other issue about this.

**Comment by iububble** [comment]
Rep.tsx 파일에서 text출력 부분을 css의 whitespace 속성을 통해서 개행 및 띄어쓰기가 그대로 반영되도록 수정했습니다.

**Comment by lifthus** [comment]
@iububble post 브랜치에 적용됐나요?

**Comment by iububble** [comment]
@lifthus  브랜치를 잘못 건드려서 날리고 다시해서 지금 #20/Bug/postText branch에 적용시켜놨습니다!

**Comment by lifthus** [comment]
👍
